import { Command } from "commander";
import { deposit, listDeposits } from "@/voidify/deposit.js";
import { parseUnits } from "@/utils/amount.js";
import { Note } from "@/utils/note.js";
import {
  createServiceContext,
  SOL_DECIMALS,
  type GlobalOptions,
} from "@/cli/helpers.js";
import { createCliProgressBar } from "@/cli/progress.js";

export function registerDepositCommands(program: Command): void {
  const depositCommand = new Command("deposit")
    .enablePositionalOptions()
    .argument("<amount>", "Deposit amount in UI units, such as 1 for 1 SOL")
    .description("Deposit commands");

  depositCommand.option(
    "-c, --commitment <string>",
    "Commitment generated by the note gen command; if omitted, a new one is generated and printed",
  );

  depositCommand
    .command("list <amount>")
    .description(
      "List records for a denomination pool, using UI units such as 1 for 1 SOL",
    )
    .option("--offset <number>", "Pagination offset")
    .option("--limit <number>", "Page size")
    .option("-o, --output <file>", "Write output to a file")
    .action(async (amount, options) => {
      try {
        const ctx = await createServiceContext(program.opts<GlobalOptions>());
        const progress = createCliProgressBar("Sync deposits");
        const deposits = await (async () => {
          try {
            return await listDeposits(ctx, parseUnits(amount, SOL_DECIMALS), {
              offset:
                options.offset !== undefined
                  ? parseInt(options.offset)
                  : undefined,
              limit:
                options.limit !== undefined
                  ? parseInt(options.limit)
                  : undefined,
              output: options.output,
              sync: { reporter: progress },
            });
          } finally {
            progress.finish();
          }
        })();
        if (!options.output) {
          console.log("Deposit records:", deposits);
        }
      } catch (error) {
        console.error("List deposits failed:", error);
        process.exit(1);
      }
    });

  depositCommand.action(async (amount: string | undefined, options) => {
    if (!amount) {
      depositCommand.help({ error: true });
      return;
    }

    try {
      const ctx = await createServiceContext(program.opts<GlobalOptions>());
      let commitment: string = options.commitment;
      if (!commitment) {
        const note = await Note.generate(amount);
        commitment = note.commitment;
        console.log("Note generated:", {
          note: note.serialize(),
          commitment: note.commitment,
        });
      }
      const txSignature = await deposit(
        ctx,
        commitment,
        parseUnits(amount, SOL_DECIMALS),
      );
      console.log("Transaction successful:", { txSignature });
    } catch (error) {
      console.error("Deposit failed:", error);
      process.exit(1);
    }
  });

  program.addCommand(depositCommand);
}
